### Regression Problem

In [1]:
import numpy as np
import pandas as pd


In [2]:
df = pd.DataFrame([[8,8,4], [7,9,5], [6,10,6], [5, 12,7]], columns=['cgpa','profile_score', 'lpa'])


In [3]:
df


cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [4]:
# initializing the parameters (weights and biases)

def initialize_parameters(layer_dims): # layer_dims: # i/p parameters at each layer in form of 1d array. In our case [2, 2, 1]
    np.random.seed(3)
    parameters = {}
    L = len(layer_dims)
    
    for l in range(1, L):
        parameters['W' + str(l)] = np.ones((layer_dims[l-1], layer_dims[l]))*0.1 # weights matrix of size [previous_layer_parameters x current_layer_parameters]
        parameters['b' + str(l)] = np.zeros((layer_dims[l], 1)) # bias matrix for current layer
        
    return parameters


In [5]:
initialize_parameters([2,2,1])


{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [6]:
# calculate the value at each neuron
def linear_forward(prev_layer_answer, W, b):
    z = np.dot(W.T, prev_layer_answer) + b
    
    return z


In [7]:
# forward propogation
def layer_forward(X, parameters): # X - row
    A = X
    L = len(parameters) // 2 # no. of layers in neural network
    
    for l in range(1, L+1):
        A_prev = A
        Wl = parameters['W' + str(l)]
        bl = parameters['b' + str(l)]
        
        print('A'+str(l-1)+': ', A_prev)
        print('W'+str(l)+': ', Wl)
        print('b'+str(l)+': ', bl)
        print('--'*15)
        
        A = linear_forward(A_prev, Wl, bl)
        print('A'+str(l)+": ", A)
        print("**"*15)
        
    return A, A_prev # since we need output at every layer to calculate loss


In [8]:
X = df[['cgpa', 'profile_score']].values[0].reshape(2, 1) # shape: [#feature x #training examples]
y = df[['lpa']].values[0][0]

# params init
parameters = initialize_parameters([2,2,1])


In [9]:
X


array([[8],
       [8]], dtype=int64)

In [10]:
y_hat, A1 = layer_forward(X, parameters)


A0:  [[8]
 [8]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
------------------------------
A1:  [[1.6]
 [1.6]]
******************************
A1:  [[1.6]
 [1.6]]
W2:  [[0.1]
 [0.1]]
b2:  [[0.]]
------------------------------
A2:  [[0.32]]
******************************


In [11]:
# loss
(y - 0.32)**2


13.5424

In [12]:
# calculate loss and update weights and biases
def update_parameters(parameters, y, y_hat, A1, X):
    parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y - y_hat) * A1[0][0])
    parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat) * A1[1][0])
    parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat))
    
    parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * 2 * (y - y_hat) * parameters['W2'][0][0] * X[0][0])
    parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001 * 2 * (y - y_hat) * parameters['W2'][0][0] * X[1][0])
    parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 * 2 * (y - y_hat) * parameters['W2'][0][0])
    
    parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001 * 2 * (y - y_hat) * parameters['W2'][1][0] * X[0][0])
    parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 * 2 * (y - y_hat) * parameters['W2'][1][0] * X[1][0])
    parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001 * 2 * (y - y_hat) * parameters['W2'][1][0])


In [13]:
y_hat = y_hat[0][0]


In [14]:
update_parameters(parameters, y, y_hat, A1, X)
parameters


{'W1': array([[0.10658137, 0.10658137],
        [0.10658137, 0.10658137]]),
 'b1': array([[0.00082267],
        [0.00082267]]),
 'W2': array([[0.111776],
        [0.111776]]),
 'b2': array([[0.119136]])}

we can see the parameters are changed now

In [15]:
# for 2nd row
X = df[['cgpa', 'profile_score']].values[1].reshape(2, 1) # shape: [#feature x #training examples]
y = df[['lpa']].values[1][0]

y_hat, A1 = layer_forward(X, parameters)


A0:  [[7]
 [9]]
W1:  [[0.10658137 0.10658137]
 [0.10658137 0.10658137]]
b1:  [[0.00082267]
 [0.00082267]]
------------------------------
A1:  [[1.70612461]
 [1.70612461]]
******************************
A1:  [[1.70612461]
 [1.70612461]]
W2:  [[0.111776]
 [0.111776]]
b2:  [[0.119136]]
------------------------------
A2:  [[0.50054357]]
******************************


In [16]:
update_parameters(parameters, y, y_hat, A1, X)


In [17]:
parameters


{'W1': array([[0.11458955, 0.1168776 ],
        [0.11458955, 0.1168776 ]]),
 'b1': array([[0.0019667],
        [0.0019667]]),
 'W2': array([[0.12712927],
        [0.12712927]]),
 'b2': array([[0.13612818]])}

In [18]:
# fro 3rd row
X = df[['cgpa', 'profile_score']].values[2].reshape(2, 1) # shape: [#feature x #training examples]
y = df[['lpa']].values[2][0]

y_hat, A1 = layer_forward(X, parameters)


A0:  [[ 6]
 [10]]
W1:  [[0.11458955 0.1168776 ]
 [0.11458955 0.1168776 ]]
b1:  [[0.0019667]
 [0.0019667]]
------------------------------
A1:  [[1.83539945]
 [1.87200826]]
******************************
A1:  [[1.83539945]
 [1.87200826]]
W2:  [[0.12712927]
 [0.12712927]]
b2:  [[0.13612818]]
------------------------------
A2:  [[0.6074482]]
******************************


In [19]:
update_parameters(parameters, y, y_hat, A1, X)

parameters


{'W1': array([[0.12409711, 0.13272353],
        [0.12412266, 0.13276611]]),
 'b1': array([[0.00355129],
        [0.00355555]]),
 'W2': array([[0.14692424],
        [0.14731907]]),
 'b2': array([[0.15810417]])}

In [20]:
# for 4th row
X = df[['cgpa', 'profile_score']].values[3].reshape(2, 1) # shape: [#feature x #training examples]
y = df[['lpa']].values[3][0]

y_hat, A1 = layer_forward(X, parameters)


A0:  [[ 5]
 [12]]
W1:  [[0.12409711 0.13272353]
 [0.12412266 0.13276611]]
b1:  [[0.00355129]
 [0.00355555]]
------------------------------
A1:  [[2.11350869]
 [2.26036654]]
******************************
A1:  [[2.11350869]
 [2.26036654]]
W2:  [[0.14692424]
 [0.14731907]]
b2:  [[0.15810417]]
------------------------------
A2:  [[0.80162493]]
******************************


In [21]:
update_parameters(parameters, y, y_hat, A1, X)

parameters


{'W1': array([[0.13482804, 0.15847776],
        [0.1349909 , 0.15884991]]),
 'b1': array([[0.00569748],
        [0.0057292 ]]),
 'W2': array([[0.17312488],
        [0.17534027]]),
 'b2': array([[0.18773702]])}

In [22]:
# final implementation with epochs

parameters = initialize_parameters([2,2,1])
epochs = 5

for i in range(epochs):
    loss = 0
    
    for j in range(df.shape[0]):
        X = df[['cgpa', 'profile_score']].values[j].reshape(2, 1)
        y = df[['lpa']].values[j][0]
        
        # forward prop.
        y_hat, A1 = layer_forward(X, parameters)
        y_hat = y_hat[0][0]
        
        # calc. loss 
        loss = loss + (y - y_hat)**2
        
        # update parameters
        update_parameters(parameters, y, y_hat, A1, X) 
        
    avg_loss = loss / df.shape[0]
    print("Epoch - ", i+1, "Loss: ", avg_loss)

print('final parameters: ')
print(parameters)


A0:  [[8]
 [8]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
------------------------------
A1:  [[1.6]
 [1.6]]
******************************
A1:  [[1.6]
 [1.6]]
W2:  [[0.1]
 [0.1]]
b2:  [[0.]]
------------------------------
A2:  [[0.32]]
******************************
A0:  [[7]
 [9]]
W1:  [[0.10658137 0.10658137]
 [0.10658137 0.10658137]]
b1:  [[0.00082267]
 [0.00082267]]
------------------------------
A1:  [[1.70612461]
 [1.70612461]]
******************************
A1:  [[1.70612461]
 [1.70612461]]
W2:  [[0.111776]
 [0.111776]]
b2:  [[0.119136]]
------------------------------
A2:  [[0.50054357]]
******************************
A0:  [[ 6]
 [10]]
W1:  [[0.11458955 0.1168776 ]
 [0.11458955 0.1168776 ]]
b1:  [[0.0019667]
 [0.0019667]]
------------------------------
A1:  [[1.83539945]
 [1.87200826]]
******************************
A1:  [[1.83539945]
 [1.87200826]]
W2:  [[0.12712927]
 [0.12712927]]
b2:  [[0.13612818]]
------------------------------
A2:  [[0.6074482]]
**********************

### Using Keras

In [23]:
import tensorflow as tf
from tensorflow.keras import layers, Sequential

# Define the model
model = Sequential([
    layers.Dense(2, activation='linear', input_dim=2),  # Input layer with 2 features
    layers.Dense(1, activation='linear')                                        # Output layer (e.g., regression)
])


In [24]:

model.summary()


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 2)                 6         
                                                                 
 dense_1 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________


In [25]:
model.get_weights()


[array([[-0.56701374, -0.21704948],
        [-0.4117353 ,  0.05523479]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[ 1.3884426 ],
        [-0.26267934]], dtype=float32),
 array([0.], dtype=float32)]

In [26]:
new_weights = [np.array([[0.1, 0.1],
        [0.1 ,  0.1]], dtype=np.float32),
 np.array([0., 0.], dtype=np.float32),
 np.array([[ 0.1 ],
        [0.1]], dtype=np.float32),
 np.array([0.], dtype=np.float32)]


In [ ]:
model.set_weights(new_weights)


In [28]:
model.get_weights()


[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [30]:
optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error', optimizer=optimizer)


In [32]:
model.fit(df.iloc[:, 0:-1].values, df['lpa'].values, epochs=50, verbose=1, batch_size=1)


Epoch 1/50
4/4 [==============================] - 0s 2ms/step - loss: 16.9795
Epoch 2/50
4/4 [==============================] - 0s 2ms/step - loss: 16.4679
Epoch 3/50
4/4 [==============================] - 0s 2ms/step - loss: 15.9030
Epoch 4/50
4/4 [==============================] - 0s 2ms/step - loss: 15.4196
Epoch 5/50
4/4 [==============================] - 0s 2ms/step - loss: 14.8456
Epoch 6/50
4/4 [==============================] - 0s 1ms/step - loss: 14.3273
Epoch 7/50
4/4 [==============================] - 0s 2ms/step - loss: 13.8459
Epoch 8/50
4/4 [==============================] - 0s 1ms/step - loss: 13.3035
Epoch 9/50
4/4 [==============================] - 0s 2ms/step - loss: 12.7856
Epoch 10/50
4/4 [==============================] - 0s 1ms/step - loss: 12.3145
Epoch 11/50
4/4 [==============================] - 0s 2ms/step - loss: 11.7751
Epoch 12/50
4/4 [==============================] - 0s 1ms/step - loss: 11.2618
Epoch 13/50
4/4 [==============================] - 0s 2ms/ste

In [33]:
model.get_weights()


[array([[0.37360412, 0.37360412],
        [0.3657724 , 0.3657724 ]], dtype=float32),
 array([0.27239046, 0.27239046], dtype=float32),
 array([[0.37301174],
        [0.37301174]], dtype=float32),
 array([0.20491731], dtype=float32)]